@url = http://localhost:3724

### BASE
{{url}}

### GET test
GET {{url}}/test

### GET flashCards
GET {{url}}/flashcards


### GET flashCard
GET {{url}}/flashcards/2798

### ALL FLASHCARDS IN A CATEGORY 
GET {{url}}/flashcards/categories/emmet

### GET Categories
GET {{url}}/categories